# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a25ba6ea441fd866595dc01f026a734013fa0b8700556589adf882fc3cb86f6f1251fb62d880c298f319f4054471f92c0a0197d542f28ccf7987606ad1e65d30

test:
  secret_key_base: 28c45b116da9cb1a5db69f9d0af9478a0c2cc12c4fd09c3ba5c594133a2a57f0ce2ee5b7bd41b78aed6c03123290e016fa2b364aef0b80d74f0140fe33980ad1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
